# Energy
oil and gas:
  - APA
  - BKR
  - COP
  - CTRA
  - CVX
  - DVN
  - EOG
  - EQT
  - EXE
  - FANG
  - HAL
  - KMI
  - MPC
  - OKE
  - OXY
  - PSX
  - SLB
  - TPL
  - TRGP
  - VLO
  - WMB
  - XOM
renewable energy:
  - FSLR
  - GE
  - TSLA

# Materials
chemicals:
  - ALB
  - APD
  - CF
  - CTVA
  - CVX
  - DD
  - DOW
  - ECL
  - IFF
  - LIN
  - LYB
  - MOS
  - PPG
  - PSX
  - SHW
  - XOM
metals and mining:
  - CAT
  - CRH
  - FCX
  - MLM
  - NEM
  - NUE
  - STLD
  - VMC

# Industrials
aerospace and defense:
  - AXON
  - BA
  - GD
  - GE
  - HII
  - HON
  - HWM
  - LHX
  - LMT
  - NOC
  - RTX
  - TDG
  - TXT
manufacturing:
  - ALLE
  - AME
  - AOS
  - BA
  - BLDR
  - CARR
  - CAT
  - CMI
  - CPRT
  - CTAS
  - DE
  - DOV
  - DOW
  - EFX
  - EME
  - EMR
  - ETN
  - FAST
  - FIX
  - GEV
  - GNRC
  - GPN
  - GWW
  - HD
  - HON
  - HUBB
  - IEX
  - INTC
  - IR
  - ITW
  - J
  - JCI
  - LII
  - MAS
  - MMM
  - NDSN
  - OTIS
  - PCAR
  - PH
  - PNR
  - POOL
  - PWR
  - ROK
  - RSG
  - RTX
  - SNA
  - SWK
  - TMO
  - TT
  - URI
  - VLTO
  - VRSK
  - VRT
  - WM
  - XYL
transportation and logistics:
  - BA
  - CHRW
  - CSX
  - DAL
  - EXPD
  - FDX
  - JBHT
  - LUV
  - NSC
  - ODFL
  - UAL
  - UNP
  - UPS
  - WAB

# Consumer Discretionary
automobiles:
  - APTV
  - AZO
  - CVNA
  - F
  - GM
  - GPC
  - ORLY
  - TSLA
retail and e-commerce:
  - AMZN
  - BBY
  - COST
  - DASH
  - DECK
  - DG
  - DHI
  - DLTR
  - EBAY
  - HD
  - KO
  - LEN
  - LOW
  - LULU
  - NKE
  - NVR
  - PEP
  - PHM
  - RL
  - ROST
  - TGT
  - TJX
  - TPR
  - TSCO
  - ULTA
  - WMT
  - WSM
hotels and leisure:
  - ABNB
  - BKNG
  - CCL
  - CMG
  - DIS
  - DPZ
  - DRI
  - EXPE
  - HAS
  - HLT
  - LVS
  - MAR
  - MCD
  - MGM
  - NCLH
  - RCL
  - SBUX
  - WYNN
  - YUM

# Consumer Staples
food and beverage:
  - CAG
  - COST
  - CPB
  - GIS
  - HRL
  - HSY
  - KDP
  - KHC
  - KO
  - KR
  - MDLZ
  - MKC
  - MNST
  - MO
  - PEP
  - PM
  - SJM
  - STZ
  - SYY
  - TAP
  - UBER
household and personal products:
  - AMCR
  - AVY
  - BALL
  - CHD
  - CL
  - CLX
  - EL
  - IP
  - JNJ
  - KMB
  - KVUE
  - PG
  - PKG
  - ROL
  - SW
agriculture:
  - ADM
  - BG
  - DE
  - PEP
  - TSN

# Health Care
pharmaceuticals and biotech:
  - A
  - ABBV
  - ABT
  - AMGN
  - BIIB
  - BMY
  - CRL
  - DGX
  - DHR
  - GILD
  - IDXX
  - INCY
  - IQV
  - JNJ
  - LH
  - LLY
  - MRK
  - MRNA
  - MTD
  - PFE
  - REGN
  - RVTY
  - TECH
  - TMO
  - VRTX
  - VTRS
  - WAT
  - ZTS
medical devices:
  - ABT
  - ALGN
  - BAX
  - BDX
  - BSX
  - COO
  - DXCM
  - EW
  - GEHC
  - HOLX
  - ISRG
  - JNJ
  - MDT
  - PODD
  - RMD
  - SOLV
  - STE
  - SYK
  - WST
  - ZBH
health services:
  - CAH
  - CI
  - CNC
  - COR
  - CVS
  - DVA
  - ELV
  - HCA
  - HSIC
  - HUM
  - MCK
  - UHS
  - UNH

# Financials
banking:
  - AAPL
  - AXP
  - BAC
  - BK
  - C
  - CFG
  - COF
  - FITB
  - HBAN
  - JPM
  - KEY
  - MA
  - MTB
  - PNC
  - PYPL
  - RF
  - SYF
  - TFC
  - USB
  - V
  - WFC
insurance:
  - ACGL
  - AFL
  - AIG
  - AIZ
  - AJG
  - ALL
  - AON
  - BRO
  - CB
  - CINF
  - EG
  - ERIE
  - GL
  - HIG
  - L
  - MET
  - MRSH
  - PGR
  - PRU
  - TRV
  - WRB
  - WTW
asset management:
  - AMP
  - APO
  - ARES
  - BEN
  - BLK
  - BX
  - CBOE
  - CME
  - COIN
  - FDS
  - GS
  - HOOD
  - IBKR
  - ICE
  - IVZ
  - KKR
  - MCO
  - MS
  - MSCI
  - NDAQ
  - NTRS
  - PFG
  - RJF
  - SCHW
  - SPGI
  - STT
  - TROW

# Information Technology
software:
  - AAPL
  - ACN
  - ADBE
  - ADP
  - ADSK
  - AKAM
  - AMZN
  - AVGO
  - BLK
  - BR
  - CDNS
  - CDW
  - CPAY
  - CRM
  - CRWD
  - CTSH
  - DDOG
  - DE
  - EPAM
  - FFIV
  - FICO
  - FIS
  - FTNT
  - GDDY
  - GEN
  - GOOG
  - GOOGL
  - GS
  - HON
  - IBM
  - INTU
  - IT
  - JKHY
  - JPM
  - LDOS
  - LMT
  - META
  - MSFT
  - NFLX
  - NOW
  - NTAP
  - NVDA
  - ORCL
  - PANW
  - PAYX
  - PLTR
  - PTC
  - ROP
  - SNPS
  - TSLA
  - TYL
  - UBER
  - VRSN
  - WDAY
  - WMT
  - XYZ
semiconductors:
  - AAPL
  - ADI
  - AMAT
  - AMD
  - AVGO
  - GOOG
  - GOOGL
  - INTC
  - KLAC
  - LRCX
  - MCHP
  - MPWR
  - MSFT
  - MU
  - NVDA
  - NXPI
  - ON
  - Q
  - QCOM
  - SWKS
  - TER
  - TXN
hardware and IT equipment:
  - AAPL
  - ANET
  - APH
  - CIEN
  - COHR
  - CSCO
  - DELL
  - FTV
  - GLW
  - GRMN
  - HPE
  - HPQ
  - IBM
  - JBL
  - KEYS
  - LITE
  - MSI
  - ORCL
  - SMCI
  - SNDK
  - STX
  - TDY
  - TEL
  - TRMB
  - WDC
  - ZBRA

# Communication Services
telecom:
  - CHTR
  - CMCSA
  - SATS
  - T
  - TMUS
  - VZ
media and entertainment:
  - AAPL
  - AMZN
  - APP
  - DIS
  - EA
  - FOX
  - FOXA
  - GOOG
  - GOOGL
  - LYV
  - META
  - MSFT
  - NFLX
  - NWS
  - NWSA
  - OMC
  - PSKY
  - T
  - TKO
  - TTD
  - TTWO
  - WBD
internet platforms:
  - CMCSA
  - DIS
  - GOOG
  - GOOGL
  - META
  - TMUS

# Utilities
electric utilities:
  - AEE
  - AEP
  - AES
  - CEG
  - CMS
  - CNP
  - D
  - DTE
  - DUK
  - ED
  - EIX
  - ES
  - ETR
  - EVRG
  - EXC
  - FE
  - LNT
  - NEE
  - NRG
  - PCG
  - PEG
  - PNW
  - PPL
  - SO
  - SRE
  - VST
  - WEC
  - XEL
gas and water utilities:
  - ATO
  - AWK
  - NI

# Real Estate
REITs:
  - AMT
  - ARE
  - AVB
  - BXP
  - CCI
  - CPT
  - DLR
  - DOC
  - EQIX
  - EQR
  - ESS
  - EXR
  - FRT
  - HST
  - INVH
  - IRM
  - KIM
  - MAA
  - O
  - PLD
  - PSA
  - REG
  - SBAC
  - SPG
  - UDR
  - VICI
  - VTR
  - WELL
  - WY
real estate services:
  - CBRE
  - CSGP
  - MCD
