IPTC news categories: #economy, business and finance
  # 상품 및 서비스
  products and Services:
    agriculture:
    business service:
    chemicals:
    computing and IT:
    construction and property:
    consumer goods:
    beverage and grocery:
    energy and resource:
    financial service:
    healthcare:
    manufacturing:
    media and entertainment:
    tourism and leisure industry:
    transportation:
    utilities: